"""added director's field

Revision ID: 734db5ec5017
Revises: 
Create Date: 2020-08-17 15:12:29.855507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734db5ec5017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('director', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'director')
    # ### end Alembic commands ###
